//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuocHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NuocHoa()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public string MaNuocHoa { get; set; }
        public string TenNuocHoa { get; set; }
        public int MaTheLoai { get; set; }
        public string NhanHieu { get; set; }
        public string XuatXu { get; set; }
        public int SoLuongHienTai { get; set; }
        public string DungTich { get; set; }
        public double GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
